# Reduced version of bin/conda.yml
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-pack=0.6.0
  - pyarrow=1.0.0
  - pandas=0.25.3
  - lightgbm=2.3.1
  - scikit-learn=0.24.2
  - hyperopt=0.2.5
  - category_encoders=2.2.2
  - imbalanced-learn=0.8.0
  - python-Levenshtein=0.12.0
  - matplotlib=3.2.2
  - numpy=1.19.5

