language: python

dist: trusty

sudo: false

notifications:
  email: false

python:
  - "3.6"

jdk:
  - openjdk8

branches:
  only:
    - master

# In TravisCI, conda fails because of `InvalidSpecError: Invalid spec: =20190808`,
# so we use pip instead.
install:
  - pip install -r ./bin/requirements.txt

script:
  # oraclejdk8 enabled by default, so we switch it to openjdk8
  - java -version
  - jdk_switcher use openjdk8
  - ./bin/run-travis-tests.sh

# after_success:
#   - mvn clean cobertura:cobertura coveralls:report

