name: Build and test

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # TODO: On jdk9+, Pandas UDF does not work correctly
        # because of Arrow integration.
        # java: [1.8, 11]
        java: [1.8]
        python: [3.6, 3.7, 3.8]
    env:
      CONDA_DISABLED: 1
    steps:
      - name: Checkout Scavenger repository
        uses: actions/checkout@v2
        # In order to fetch changed files
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Install Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - name: Install Python packages (Python ${{ matrix.python }})
        run: python -m pip install -r ./bin/requirements.txt
      - name: Run tests
        run: |
          ./build/mvn -q clean package
          ./bin/run-tests

